# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogProcCrea.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DiaProcCrea(object):
    def setupUi(self, DiaProcCrea):
        DiaProcCrea.setObjectName("DiaProcCrea")
        DiaProcCrea.resize(388, 155)
        self.buttonBox = QtWidgets.QDialogButtonBox(DiaProcCrea)
        self.buttonBox.setGeometry(QtCore.QRect(290, 20, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(DiaProcCrea)
        self.label.setGeometry(QtCore.QRect(10, 10, 54, 12))
        self.label.setObjectName("label")
        self.lineName = QtWidgets.QLineEdit(DiaProcCrea)
        self.lineName.setGeometry(QtCore.QRect(60, 10, 113, 20))
        self.lineName.setObjectName("lineName")
        self.label_3 = QtWidgets.QLabel(DiaProcCrea)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 54, 12))
        self.label_3.setObjectName("label_3")
        self.lineCon = QtWidgets.QLineEdit(DiaProcCrea)
        self.lineCon.setGeometry(QtCore.QRect(60, 40, 113, 20))
        self.lineCon.setObjectName("lineCon")

        self.retranslateUi(DiaProcCrea)
        self.buttonBox.accepted.connect(DiaProcCrea.accept)
        self.buttonBox.rejected.connect(DiaProcCrea.reject)
        QtCore.QMetaObject.connectSlotsByName(DiaProcCrea)

    def retranslateUi(self, DiaProcCrea):
        _translate = QtCore.QCoreApplication.translate
        DiaProcCrea.setWindowTitle(_translate("DiaProcCrea", "进程创建"))
        self.label.setText(_translate("DiaProcCrea", "进程名"))
        self.label_3.setText(_translate("DiaProcCrea", "内容"))
